### ISSUE TITLE
GMT-MEX API is failed when using grdimage

### ISSUE THREAD

**Issue by chiyu-chiu** [GenericMappingTools/gmtmex#2]
Hello,

    I tried to use GMT-MEX API on MacOS 10.13 with MATLAB R2018b. When I execute these commands, it reports the error message as following,

    t = rand(100,3) * 150;
    G = gmt('surface -R0/150/0/150 -I1', t);
    gmt('grdimage -JX8c -Ba -P -Cblue,red -G > crap_img.ps', G)
    [Session Matlab (2)]: Error returned from GMT API: GMT_OBJECT_NOT_FOUND (59)
    Error using gmtmex
    GMT: Failure to open virtual file
    Error in gmt (line 33)
		[varargout{1:nargout}] = gmtmex (cmd, varargin{:});

    The GMT version on my laptop is 6.0.0_c1a5c7c. Would you help me fix this problem?

    With Regards,
    Chi-Yu Chiu

**Comment by joa-quim** [comment]
To run with GMT6 (master) you need to build the GMTMEX from the master branch as well. If you have a gmtmex built for 5.4 it won't work.
