### ISSUE TITLE
Location of gmtmex.mexw64 file

### ISSUE THREAD

**Issue by Jbarrers9740** [GenericMappingTools/gmtmex#27]
**Description of the problem**
I am trying to install gmtmex for MatLab in my Windows computer. However, I cannot find the gmtmex.mexw64 anywhere. Can somebody tell me how to get such file?

**Comment by joa-quim** [comment]
The gmtmex comes included with the GMTinstaller so you only have to add the ``c:\programs\gmt6\bin`` to your Matlab path and things are ready to run.

**Comment by Jbarrers9740** [comment]
Thank you so much! I am gonna close this issue.
