### ISSUE TITLE
calling pstext using a cell array makes MATLAB crash

### ISSUE THREAD

**Issue by bridgeW** [GenericMappingTools/gmtmex#32]
**Description of the problem**

 I'm using the gmtmex of MATLAB-API. I encountered a calling problem that made MATLAB crash.
    I've tried different ways of putting data into a cell array according to the paper (Wessel and Luis, 2017). This is the code:
      
     txt = {[110, 30], 'CIRCULAR'};
     gmt(['pstext -R -J -O >> ' outfn '.ps'], txt{1, :});

this code didn't make MATLAB crash ever. (see the complete code following)  

**Full script that generated the error**

However, it throw an ERROR message:

" pstext [ERROR]: Text record line 0 is NULL! Skipped but this is trouble)".

```
outfn = 'ex2HL_arrows'; % must single quotaion

gmt('pscoast -R70/150/0/60 -JM15c -Ba -A4000 -N1 -W0.25p,black -K > ex2HL_arrows.ps')
%% plot 12 Cartesian vectors with different lengths
x = linspace(109, 109, 12)';
y = linspace(30, 50, 12)';
direction = zeros(size(x));
length = linspace(0.5, 1.5, 12)';
% Cartesian vectors (v) with red pen and fill (+g, +p), vector head at
% end (+e), and 40 degree angle (+a) with no indentation for vector head (+h)
style = 'v0.2c+e+a40+gred+h0+p1p,red';
vector = [x y direction length];
% gmt('psxy', ['-R20/60/-180/0 -JM12c -W1p,red -S' style  ' > ' outfn '.ps'], vector);
gmt(['psxy -R -J -Ba -W1p,red -S' style ' -K -O >> ' outfn '.ps'], vector);


%% plot 7 math angle arcs with different radii
num = 7;
x = linspace(95, 95, num)'; % x coordinates of the center
y = linspace( 37, 37, num)';  %# y coordinates of the center
radius = 1.8 - 0.2 * (0 : num - 1)';%  # radius
startdir = linspace(90, 90, num)';  % #start direction in degrees
stopdir = 180 + 40 * (0 : num - 1)';  %# stop direction in degrees
%# data for circular vectors
data = [x y radius startdir stopdir];
arcstyle = 'm0.5c+ea';  %# Circular vector (m) with an arrow at end
gmt(['psxy -R -J -Gred3 -W1.5p,black -S' arcstyle ' -K -O >> ' outfn '.ps'], data)


%% plot geographic vectors using endpoints
PEK = [116.41, 39.9]; % Peking
XAN = [108.9, 34.3];  % Xi'an
XJG = [87.62, 43.79]; % XinJiang
KMG = [102.71, 25.04]; % KunMing
% `=` means geographic vectors.
% With the modifier '+s', the input data should contain coordinates of start
% and end points
style = '=0.5c+s+e+a30+gblue+h0.5+p1p,blue';
data = [[PEK  XAN]; [PEK  XJG]; [PEK  KMG]];
gmt(['psxy -R -J -S' style ' -W1.0p,blue -K -O >> ' outfn '.ps'], data);
txt = {[110, 30], 'CIRCULAR'};
%gmt(['pstext -R -J -F+f13p,Helvetica-Bold,red -O >> ' outfn '.ps'], txt);
gmt(['pstext -R -J -O >> ' outfn '.ps'], txt(1, :));

gmt(['psconvert -A -Tg -E600 ' outfn '.ps']);
gmt(['psconvert -A -Tgf ' outfn '.ps']);
gmt('destroy');
open([outfn '.pdf']);




```

**Full error message**

```
 pstext [ERROR]: Text record line 0 is NULL! Skipped but this is trouble)
```

**System information**

* Operating system: Win10
* Version of GMT: gmt 6.3
* Version of GMTMex: gmt6.3
* MATLAB version: 2021b

**Comment by bridgeW** [comment]
my matlab plot code comes from https://www.pygmt.org/latest/gallery/lines/vector_styles.html#sphx-glr-gallery-lines-vector-styles-py.

**Comment by joa-quim** [comment]
Yes, it crashes and that's not good (thanks for catching this) but although I'm a bit rusty with GMTMEX this is not a valid syntax:
```
gmt(['pstext -R -J -O >> ' outfn '.ps'], txt(1, :));
```
it should instead be
```
R = gmt('record', [110 30], 'CIRCULAR');       % Need to create a text structure to pass to pstext
gmt(['pstext -R -J -O >> ' outfn '.ps'], R);
```
and with it, your example works.

**Comment by joa-quim** [comment]
Honestly I think maybe not. Need to not forget that we are creating (well, extending) a maintenance burden.

**Comment by bridgeW** [comment]
> Yes, it crashes and that's not good (thanks for catching this) but although I'm a bit rusty with GMTMEX this is not a valid syntax:
> 
> ```
> gmt(['pstext -R -J -O >> ' outfn '.ps'], txt(1, :));
> ```
> 
> it should instead be
> 
> ```
> R = gmt('record', [110 30], 'CIRCULAR');       % Need to create a text structure to pass to pstext
> gmt(['pstext -R -J -O >> ' outfn '.ps'], R);
> ```
> 
> and with it, your example works.

works! thank you very much~
