### ISSUE TITLE
Version /gmt/opt is not listed among recognized GMT versions

### ISSUE THREAD

**Issue by 15901892** [GenericMappingTools/gmtmex#4]
**Description of the problem**

I installed the GMT latest vesrsion and have matlab on my Mac. Now I want to install the GMT API for matlab. After installation of gmt_prepmex.sh, it gives me following error on next step. Please help

```
Version /gmt/opt is not listed among recognized GMT versions.
Run gmtswitch -help for more information
```
**System information**

* Operating system: Mac
* Version of GMT:  5.4.4 (r20314)
* Version of GMTMex: Don't know how to get this info

**Comment by PaulWessel** [comment]
You need to create a file in your home directory called .gmtversions and list the paths that contain the binary directory for each of the GMT versions you have, even if just one.  It should have one line per version.  Mine looks like this:

```
/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt-dev/dbuild/gmt6
/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/gmt4-dev
/opt/gmt

```
